### ISSUE TITLE
Inactive state when requesting contacts

### ISSUE THREAD

**Issue by edo1493** [morenoh149/react-native-contacts#150]
Whenever I request permissions to access the contacts list, the app goes in "inactive" state. I am listening to this through the core api "AppState" in iOS. 

I was wondering if this is a normal behaviour, since it doesn't seem so and it's conflicting with other things that are listening to the state when it becomes "inactive". 

Thanks

**Comment by JaxGit** [comment]
Yep, at least on iOS when requesting permission and the Contacts Usage Description popping up, the app itself will go into inactive state just like you have drawn the notification tray without minimising the app, because in both cases the app is not really in background but something in a system level is covering on it. 

Maybe try recording this isRequestingPermission state also in your redux store to amend the "AppState" you want.
