### ISSUE TITLE
updateContact is only adding new information on android 

### ISSUE THREAD

**Issue by Avery246813579** [morenoh149/react-native-contacts#332]
I am using updateContact on android v28 and whenever I call updateContact it updates the contact by just adding the new element. For example, if I update with a new phone number it will add a new phone number to the contact and keep the old one. When trying to update the contact with empty array for say the phoneNumbers, nothing is changed and all contacts would be the same. So it seems instead of deleting the old elements inside the array, it just adds new ones and keeps the old ones. 

The feature works as intended on iOS.

**Comment by morenoh149** [comment]
Sounds like update behaves like a PUT on Android but not iOS. Intended beshvior is to act like a POST on both platforms. Bug.

**Comment by jamalhassouni** [comment]
@Avery246813579  same error here

**Comment by Git-Hub-Admin** [comment]
Also running into the same issue.

**Comment by luucv** [comment]
Same here, did one of you find a fix? @Git-Hub-Admin @jamalhassouni @Avery246813579

**Comment by Git-Hub-Admin** [comment]
Looking at the code in ContactsManager.java, updateContact will look for the "id" value of each of the phoneNumber/emails/postalAddress in your update argument.  If the id is not provided, it will run ContentProviderOperation.newInsert instead of ContentProviderOperation.newUpdate. (which makes sense, otherwise, you cannot identify the specific number you want to update).

What this means is by calling 
 `Contacts.updateContact(
    {emailAddresses:
        [{label: "junk",
         email: "mrniet+junkmail@test.com"}]
   }
  ),`
You will always end up invoking newInsert because id is not provided.

What's you need to call is 
 `Contacts.updateContact(
    {emailAddresses:
        [{id: 'the id of the email record in contact',
         label: "junk",
         email: "mrniet+junkmail@test.com"}]
   }
  ),`

The id of each email/phone/address is not retrieved from getAll according to the documentation. But in practice, it is indeed retrieved. So make sure you call updateContact with the id of that phone number/email address/postal address, and it will update that specific one.  I'm not sure how it works for iOS yet, and whether the documentation needs to be updated accordingly.

I am assuming that 
  `{emailAddresses:
    [{id: 190, label: "" email:""}]
  }`
will delete the emailAddress with id 190. But I have yet to test on that. Otherwise, there's no way to delete phone/email/address.

Also, will this be consistent with behaviors in iOS, does it do a complete overwrite for iOS contact as opposed to the id specified update? I'll try to read through the iOS code and update on this if noone else has answered this question by then.

**Comment by luucv** [comment]
In iOS it does indeed look like it rewrites the entire contact, since it doesn't have the 'id' for each phone number/email. 

I forked this repo and adjusted the android functionality to fit my use case and be more consistent with iOS: it removes all the `phoneNumbers` and `email` entries, then adds the given entries again. I think this should happen for more fields on android but will dig into that later.

https://github.com/luucv/react-native-contacts

**Comment by morenoh149** [comment]
@Git-Hub-Admin So we need email address ids in order to update email addresses on a contact? Please help by submitting a PR to update the readme. Or a self contained blurb explaining how to get the desired effect. I don't want to misinterpret your findings.

**Comment by Git-Hub-Admin** [comment]
@Git-Hub-Admin @luucv 

I think an opening a new issue would be great. I'm really new to open source stuff, so I don't quite know the general conventions of how things work.

I like @luucv 's approach of removing records then add them.  It keeps things consistent between platforms. In that case, the README does not need to be updated.  It does remove the possibility of update a single phone entry without having to copy over other phone entries as well, but then again,it doesn't do that in iOS either. so I think that's the best approach of addressing this problem.

So far the problems I spotted with Android in terms of update are:
1. custom labels get overwritten to "Other",
2. postal address update code doesn't exist. (it exists for addContact)
3. phoneNumbers and emails insert instead of update. 

I've forked the repo, and I can probably make a pull request with these issues addressed later today or tomorrow.

**Comment by morenoh149** [comment]
I think this issue can continue tracking the problem. We just need a PR fixing the issue by either making the api behave in an expected way and/or making the api behave the same on both platforms. PRs welcome.

**Comment by paintedbicycle** [comment]
Do any of these merges fix https://github.com/rt2zz/react-native-contacts/issues/270? Seems very similar

**Comment by morenoh149** [comment]
@paintedbicycle try them out
