### ISSUE TITLE
iOS - Wrong localization of navbarItems

### ISSUE THREAD

**Issue by francologic** [morenoh149/react-native-contacts#545]
![7610fdeb-b9bc-47f7-9065-ebea865e2cca](https://user-images.githubusercontent.com/60550704/89074983-909a5080-d353-11ea-9f71-05884d290d62.jpg)

When using openContactsForm() in devices/simulators "Done" and "Cancel" are always showing in english, even though the device is set to Portuguese.

**Comment by thijs-qv** [comment]
For anybody still wondering about this: add localization to your app (Project > Info > Localizations). If there is no localization file found which matches the device's set language, it will fall back to English.

**Comment by rcidt** [comment]
The hint @thijs-qv provided is not clear to me (I'm not very strong in iOS development).

@francologic could you please help me understand how you solved this?

Thank you!

**Comment by thijs-qv** [comment]
@rcidt You need to open your project in Xcode, make sure the project is selected (so not a target), go to the Info tab, scroll down to Localizations and add a language of your choice. Some values are included in the localization file by default, so when this file is present the buttons will be translated if the language of the localization file is the same as the device language.


![addNewLanguage](https://user-images.githubusercontent.com/52537741/142383064-0df9c940-49af-48b3-86e3-4dea09a6342d.png)

**Comment by thijs-qv** [comment]
I'm not really an expert on this, just commented what worked for me earlier. You need to have the `Use Base Internationalization` checkbox checked, I'm at least sure of that. I don't think it matters that you have `0 Files Localized` showing. Just tried adding another language to my project, and it asks which resources I want to have a localization for (for me it only shows the LaunchScreen.xib). 

The idea of adding the localization is to have the default Apple UI stuff localized, which I think should be OK without any specific resources since they are default values. Maybe you have added pr-PT and the device uses pr-BR or vice versa?

**Comment by rcidt** [comment]
I will continue messing around with the settings. Thank you for your time @thijs-qv!
